### ISSUE TITLE
id is not specified for extension /visual_studio_code_dark_plus

### ISSUE THREAD

**Issue by MrAliSalehi** [samdark/intellij-visual-studio-code-dark-plus#61]
### What the issue is?

I'm keep getting this error in new JetBrains IDE `RustRover`:
```
java.lang.Throwable: id is not specified for extension /visual_studio_code_dark_plus
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:376)
	at com.intellij.openapi.editor.colors.impl.EditorColorsManagerImplKt$createLoadBundledSchemeRequests$1$1.getSchemeKey(EditorColorsManagerImpl.kt:711)
	at com.intellij.configurationStore.schemeManager.SchemeManagerImpl.loadBundledSchemes(SchemeManagerImpl.kt:127)
	at com.intellij.openapi.editor.colors.impl.EditorColorsManagerImpl.<init>(EditorColorsManagerImpl.kt:102)
	at com.intellij.openapi.editor.colors.impl.EditorColorsManagerImpl.<init>(EditorColorsManagerImpl.kt:89)
	at com.intellij.serviceContainer.ComponentManagerImpl.findConstructorAndInstantiateClass(ComponentManagerImpl.kt:1379)
	at com.intellij.serviceContainer.ComponentManagerImpl.doInstantiateClass(ComponentManagerImpl.kt:1388)
	at com.intellij.serviceContainer.ComponentManagerImpl.instantiateClass(ComponentManagerImpl.kt:1373)
	at com.intellij.serviceContainer.ServiceComponentAdapter.doCreateInstance(ServiceComponentAdapter.kt:46)
	at com.intellij.serviceContainer.BaseComponentAdapter.doCreateInstance(BaseComponentAdapter.kt:176)
	at com.intellij.serviceContainer.BaseComponentAdapter.createInstance(BaseComponentAdapter.kt:155)
	at com.intellij.serviceContainer.BaseComponentAdapter.access$createInstance(BaseComponentAdapter.kt:23)
	at com.intellij.serviceContainer.BaseComponentAdapter$getInstanceAsync$2.invokeSuspend(BaseComponentAdapter.kt:203)
	at com.intellij.serviceContainer.BaseComponentAdapter$getInstanceAsync$2.invoke(BaseComponentAdapter.kt)
	at com.intellij.serviceContainer.BaseComponentAdapter$getInstanceAsync$2.invoke(BaseComponentAdapter.kt)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:78)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:167)
	at kotlinx.coroutines.BuildersKt.withContext(Unknown Source)
	at com.intellij.serviceContainer.BaseComponentAdapter.getInstanceAsync(BaseComponentAdapter.kt:198)
	at com.intellij.serviceContainer.ComponentManagerImpl.getServiceAsyncIfDefined(ComponentManagerImpl.kt:1007)
	at com.intellij.serviceContainer.ComponentManagerImpl.getServiceAsync(ComponentManagerImpl.kt:991)
	at com.intellij.platform.ide.bootstrap.ApplicationLoader$preInitApp$3$1.invokeSuspend(ApplicationLoader.kt:462)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
```

it doesn't cause any issue, it least im not aware of any, but it keeps opening this annoying error in the IDE.

### Additional info

| Q                | A
| ---------------- | ---
| Plugin Version   | 2.8
| IDE and version  |  `RustRover 2023.3 EAP, Build #RR-233.10527.212, built on November 25, 2023`
| Operating system | Windows 11 & Debian 12

**Comment by E011011101001** [comment]
Same bug. Appearing everytime when Clion (Nova) starts.
Also not aware of any issue.

- Plugin Version: 2.8
- IDE: CLion 2023.3 EAP (Nova) Build #CL-233.12287
- OS: Arch Linux x86_64 Kernel 6.6.4-arch1-1

**Comment by glen-84** [comment]
@samdark Any chance that this will be fixed soon?

**Comment by samdark** [comment]
@glen-84 I have no idea why it is like that. If you know why please post it here.

**Comment by glen-84** [comment]
@samdark

Seems like [it's supposed to be a warning](https://youtrack.jetbrains.com/issue/IDEA-333819/Color-schemes-from-theme-plugins-are-unavailable#focus=Comments-27-8175767.0-0).

And here's an [open issue](https://youtrack.jetbrains.com/issue/IDEA-337388/java.lang.Throwable-id-is-not-specified-for-extension-visualstudiocodedarkplus).

**Comment by samdark** [comment]
So basically ID needs to be provided by the extension, right?

**Comment by samdark** [comment]
Interesting. It is provided: https://github.com/samdark/intellij-visual-studio-code-dark-plus/blob/master/resources/META-INF/plugin.xml#L2

**Comment by glen-84** [comment]
> So basically ID needs to be provided by the extension, right?

Even then, it should just fall back to an auto-generated ID and log a warning.

> Interesting. It is provided

As mentioned, this seems like a bug in Rider.

**Comment by samdark** [comment]
Then, it seems, I can do nothing to fix it.

**Comment by rikkarth** [comment]
I had a similar error with a different theme, what I did was, I was prompted for an IntelliJ update, so I first closed IntelliJ and then started it as admin (windows), then I updated IntelliJ, during update I had a window popup telling me file conflicts found during update, I procceded with the suggested solutions on the window and the problem was fixed.

I hope it helps.

**Comment by t1u1** [comment]
If I understand [this comment](https://youtrack.jetbrains.com/issue/IJPL-54601/java.lang.Throwable-id-is-not-specified-for-extension-visualstudiocodedarkplus#focus=Comments-27-9815674.0-0) right, the plugin needs to specify an id for bundledColorScheme extension point. [Doc](https://plugins.jetbrains.com/docs/intellij/creating-theme-project.html#bundling-color-schemes)

So I guess, [this line](https://github.com/samdark/intellij-visual-studio-code-dark-plus/blob/ca4b02b5cbec38cbee6b5e60d87c70ecc91b5b40/resources/META-INF/plugin.xml#L127) needs to have an id attribute.

**Comment by glen-84** [comment]
@samdark There's an example [here](https://github.com/catppuccin/jetbrains/pull/107/files).

**Comment by rlnt** [comment]
This is still an issue. It's the only theme I have that's still throwing this exception. I was able to fix this exception in my own color scheme like this: https://github.com/rlnt/idea-relentless-colors/commit/82ae6afcd7aa92a87edaeac2031a541f5a68a610#diff-8dc406743d805206f4f3624fe496585fc68c405cdfc0ed68035a6bfff1790738R21

**Comment by LtdJorge** [comment]
#66  should fix it

**Comment by LtdJorge** [comment]
@samdark is the releasing of new versions automated with some CI or do you have to push them manually?

**Comment by LtdJorge** [comment]
Btw, this had been bugging me for a long time on RustRover, shout out to @rlnt for the actual heavy lifting :)

**Comment by MrAliSalehi** [comment]
im glad this is finally fixed, thank you all <3
